### ISSUE TITLE
Pb with accents with ggplot2 graphics

### ISSUE THREAD

**Issue by jr1234567** [daqana/tikzDevice#166] opened 2017-10-23 16:49 UTC
Using an accented "é" in the following ggplot2 graph makes R hangs when using tikzdevice,  whereas it works using simple pdf device.
(This is on Linux Mint. All packages updated.)

#######
library(tikzDevice)
library(ggplot2)

options(tikzDefaultEngine = "luatex")

tikzLualatexPackages =c(
  "\\usepackage{tikz}\n",
  "\\usepackage[active,tightpage,psfixbb]{preview}\n",
  "\\usepackage{fontspec,xunicode}\n",
  "\\PreviewEnvironment{pgfpicture}\n",
  "\\setlength\\PreviewBorder{0pt}\n"
)

x<- rnorm(10)
y<- rnorm(10)
df <- data.frame(x=x, y=y)

#### This example works, without accented glyph
tikz(standAlone = TRUE)
ggplot(df, aes(x=x, y=y))+geom_point() +xlab("e")
dev.off()
####

#### This example, with an "é" in a x-axis label, label  hangs and never completes
tikz(standAlone = TRUE)
ggplot(df, aes(x=x, y=y))+geom_point() +xlab("é")
dev.off()
####

#### Working OK when using pdf device
pdf()
ggplot(df, aes(x=x, y=y))+geom_point() +xlab("é")
dev.off()
####

Jacques

**Comment by nichtleiter** [comment] 2017-10-25 18:29
Hey my friend :)

You are not alone with this proble,. I just issued a bug report regarding the same issue. On my side german umlauts are making the problem.

However there is a workaround. You can use the indirect latex notation for accented characters like

```
tikz(standAlone = TRUE)
ggplot(df, aes(x=x, y=y))+geom_point() +xlab("\\'{e}")
dev.off()
```

This is not a permanent solution but it may help as long as the bug isn't wiped out.

**Comment by jr1234567** [comment] 2017-12-28 10:05
It would be nice if it could be fixed as it precludes using ggplot2 with tikzDevice

**Comment by krlmlr** [comment] 2018-02-03 01:34
Thanks. Can you please share the output of `tikzTest()`?

**Comment by jr1234567** [comment] 2018-02-03 07:53
Active compiler:
	/usr/local/bin/pdflatex
	pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
	kpathsea version 6.2.3

Measuring dimensions of: A
Running command: '/usr/local/bin/pdflatex' -interaction=batchmode -halt-on-error -output-directory '/tmp/Rtmp3xtfKd/tikzDevice7ca7644114a1' '/tmp/Rtmp3xtfKd/tikzDevice7ca7644114a1/tikzStringWidthCalc.tex'
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
[1] 7.49817

**Comment by Ashymad** [comment] 2018-03-17 00:45
I have the same problem with polish accented characters.
Output of tikzTest('ą')
```
Active compiler:
        /usr/bin/xelatex
        XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/Arch Linux)
        kpathsea version 6.2.3

Measuring dimensions of: ą
Running command: '/usr/bin/xelatex' -interaction=batchmode -halt-on-error -output-director
y '/tmp/RtmpUnF6PW/tikzDevice6ed2109d154d' '/tmp/RtmpUnF6PW/tikzDevice6ed2109d154d/tikzStr
ingWidthCalc.tex'
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Arch Linux) (preloaded format
=xelatex)
 restricted \write18 enabled.
entering extended mode
NULL
Warning message:
In getMetricsFromLatex(TeXMetrics, verbose = TRUE, diagnose = diagnose) :
  XeLaTeX was unable to calculate metrics for some characters:
         Missing character: There is no ą in font ec-lmr12!
```

**Comment by krlmlr** [comment] 2018-03-22 00:36
@Ashymad: "Missing character: There is no ą in font ec-lmr12!" is the crucial message, are you sure this particular character can be rendered in a .tex document?

@jr1234567: Measurement looks ok, I really have no idea what's going on.

**Comment by Ashymad** [comment] 2018-03-22 20:01
After some digging i found out that, as per [this answer on SE](https://tex.stackexchange.com/questions/311854/only-one-specific-character-missing-when-compiling-with-biber-and-xelatex/311861), `fontenc` package should not be used with unicode-capable engines, however by default `tikzUnicodeMetricPackages` does include it. If I remove it tikzTest('ą') works:
```
Active compiler:
        /usr/bin/xelatex
        XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/Arch Linux)
        kpathsea version 6.2.3

Measuring dimensions of: ą
Running command: '/usr/bin/xelatex' -interaction=batchmode -halt-on-error -output-directory '/
tmp/Rtmpde1LkS/tikzDevice176a43a9a6d5' '/tmp/Rtmpde1LkS/tikzDevice176a43a9a6d5/tikzStringWidth
Calc.tex'
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Arch Linux) (preloaded format=xel
atex)
 restricted \write18 enabled.
entering extended mode
[1] 6.75598
```
So, I suppose this should be changed. Sadly this does not help with the issue and compiling plots still hangs indefinitely :(

**Comment by krlmlr** [comment] 2018-03-23 09:27
Would you suggest changing the default set of packages for XeTeX?

Some plots do take a very long time to render the first time. Can you share a reproducible example?

**Comment by jr1234567** [comment] 2018-03-24 11:49
Curiously the problem is specific to using ggplot2, as in the following identical graphs (base, lattice and ggplot2)), only ggplot2 graphs hangs, whereas base graphics and lattice graphics works fine.
#######################
library(tikzDevice)
library(lattice)
options(tikzDefaultEngine = "luatex")

tikz(standAlone = TRUE)
xyplot(mpg ~ disp, mtcars, main="é") ##works fine
dev.off()

tikz(standAlone = TRUE)
plot(mpg ~ disp, mtcars, main="é")  ##works fine
dev.off()

tikz(standAlone = TRUE)
ggplot2::qplot(disp, mpg, data = mtcars, main="é")  ## does not end
dev.off()

**Comment by Ashymad** [comment] 2018-07-04 20:00
Although I haven't done extensive testing, it seems that this problem is fixed in the development version of ggplot2. I am able to use polish characters in labels and everything works as expected.

**Comment by bellackn** [comment] 2018-08-13 13:51
Closing this issue since it appears to be resolved. Please feel free, if this is still an issue, to leave a comment requesting this issue be reopened.

**Closed by bellackn** 2018-08-13 13:51 UTC
